# SITE CONFIGURATION
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.hacksocnotts.github.io" # the base hostname & protocol for your site

gems:
  - jekyll-paginate
  - rouge

# THEME-SPECIFIC CONFIGURATION
theme_specific:
  # Meta
  title: HackSoc
  avatar: 'avatar.png'
  gravatar: # Email MD5 hash
  description: "University of Nottingham Hack Society, HackSoc" # used by search engines

  # Header and footer text
  header_text: >
     <p>Hacking and Programming society at the University of Nottingham</p>
     <p class="mobile-hidden">Calling all HackSoc <a href="//github.com/HackSocNotts" target=\"_blank\">github members</a>,
     help us improve this website by <a target=\"_blank\" href="//github.com/HackSocNotts/HackSocNotts.github.io">submitting a change!</a></p>

     <p>We also run the <a href="http://hacknotts.com">HackNotts hackathon</a> and the <a href="http://inspirewit.com">InspireWIT conference</a>.</p>

  header_text_feature_image:
  footer_text: >
   Created by members of <a href="//github.com/orgs/HackSocNotts/people">HackSoc</a>, and available under the terms of the <a href="https://github.com/HackSocNotts/HackSocNotts.github.io/blob/master/LICENSE">GNU General Public License v3</a>.

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  facebook: "groups/hacksocNotts"
  github: "HackSocNotts"
  twitter: "hacksocnotts"
  slack: "hacksocnotts"

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: :compressed

exclude: [vendor]
