baseURL: 'http://hacksocnotts.co.uk/'
languageCode: 'en-us'
title: 'HackSoc'

enableRobotsTXT: true
buildFuture: true

params:
  description: "HackSoc Nottingham"
  # author: "HackSoc Committee"
  logoPath: "/img/logo.svg"

outputs:
  home:
    - HTML
  section:
    - Calendar
    - HTML
    - JSON
  page:
    - HTML