# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "5e:1e:3e:ba:ab:53:9a:a2:45:e7:f7:e8:8a:76:23:19"
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: node_modules/.bin/lessc src/components/pages/CalendarPage/less/styles.less > src/components/pages/CalendarPage/styles.css
      
      - run: ls

      # ESLint
      - run:
          command: |
            mkdir -p ~/reports
            node_modules/.bin/eslint ./src/ --ext .js,.jsx --format junit --output-file ~/reports/eslint/results.xml
          when: always
      # Events Manifest
      - run:
          command: |
            node scripts/validateEventsManifest.js src/_events/eventsManifest.json ~/reports/eventsManifest/results.xml
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports  

      # Build
      - run: yarn build
      - run: git config --global user.email $GH_EMAIL
      - run: git config --global user.name $GH_NAME
      # Deploy
      - deploy:
          name: Deploy to GH_Pages if tests pass and branch is Master
          command:  |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              node_modules/.bin/gh-pages -d build
            else
              echo "Not master branch so not deploying"
            fi


